Vagrant.configure("2") do |config|
  config.vm.box = "vagrant-centos-6.7.box"
  config.vm.provider "virtualbox" do |vb|
     vb.memory = "2048"
     vb.cpus = "1"
  end
  config.vm.network "private_network", ip: "192.168.33.10"
end

